# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/deeplearn-basics',
                'doc_host': 'https://yz-tsl.github.io',
                'git_url': 'https://github.com/yz-tsl/deeplearn-basics',
                'lib_path': 'deeplearn_basics'},
  'syms': {'deeplearn_basics.core': {'deeplearn_basics.core.foo': ('core.html#foo', 'deeplearn_basics/core.py')}}}
